services:
  - type: web
    name: sentiment-api
    env: python
    plan: free
    buildCommand: pip install -r sentiment_api/requirements.txt
    startCommand: uvicorn sentiment_api.main:app --host 0.0.0.0 --port 10000
